# Generated by Django 5.0.6 on 2024-07-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.TextField(blank=True)),
                ('content', models.TextField(blank=True, default='')),
                ('content_type', models.TextField(blank=True, default='text')),
                ('ban', models.BooleanField(default=False)),
                ('media_url', models.FileField(blank=True, default='', null=True, upload_to='chat/')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_record',
            },
        ),
    ]
