# Generated by Django 5.0.6 on 2024-09-10 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat_record",
            name="is_carer_user",
            field=models.BooleanField(default=False),
        ),
    ]
