# Generated by Django 5.0.6 on 2024-10-01 03:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_chat_record_is_carer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat_record",
            name="message_id",
            field=models.UUIDField(
                default=uuid.UUID("18753ba6-ba10-4ed9-a24e-8a8f842cbbbf"),
                editable=False,
            ),
        ),
    ]
