# Generated by Django 5.0.6 on 2024-10-02 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_record_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_record',
            name='message_id',
            field=models.UUIDField(default=uuid.UUID('8f26e521-2deb-49ec-9946-ef5b4343b8ab'), editable=False),
        ),
    ]
