# Generated by Django 5.0.6 on 2024-10-02 07:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_chat_record_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_record',
            name='message_id',
            field=models.UUIDField(default=uuid.UUID('14fcf056-1c4d-462b-8d75-d43860b5c5bc'), editable=False),
        ),
    ]
