# Generated by Django 5.0.6 on 2024-10-02 07:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chat_record_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_record',
            name='message_id',
            field=models.UUIDField(default=uuid.UUID('6b21b7f2-52f7-4f58-9d5a-49641ef19ca9'), editable=False),
        ),
    ]
