# Generated by Django 5.0.6 on 2024-10-02 07:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chat_record_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(blank=True)),
                ('room_path', models.TextField(blank=True, default='text')),
                ('notes', models.TextField(blank=True, default='')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'chat_room',
            },
        ),
        migrations.AlterField(
            model_name='chat_record',
            name='message_id',
            field=models.UUIDField(default=uuid.UUID('2f29691b-a48c-4c60-b844-fd95438bd65d'), editable=False),
        ),
    ]
