# Generated by Django 5.0.6 on 2024-10-02 07:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chat_room_alter_chat_record_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_record',
            name='message_id',
            field=models.UUIDField(default=uuid.UUID('722838f6-2a7e-43d2-a134-370d4a8c55b1'), editable=False),
        ),
    ]
