# Generated by Django 5.0.6 on 2024-10-04 06:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_alter_chat_record_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat_record",
            name="message_id",
            field=models.UUIDField(
                default=uuid.UUID("a1a3b1ba-ebe8-4ed7-9c32-a17f94b133a4"),
                editable=False,
            ),
        ),
    ]
