# Generated by Django 5.0.6 on 2024-10-15 07:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_alter_chat_record_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat_record",
            name="message_id",
            field=models.UUIDField(
                default=uuid.UUID("f358edbe-042a-4ac6-bba4-273a23c75460"),
                editable=False,
            ),
        ),
    ]
