# Generated by Django 5.0.6 on 2024-10-23 08:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_alter_chat_record_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat_record",
            name="message_id",
            field=models.UUIDField(
                default=uuid.UUID("7ac08fe4-f3eb-4fd0-b41e-f004b8deedfb"),
                editable=False,
            ),
        ),
    ]
