# Generated by Django 5.0.6 on 2024-12-11 10:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_alter_chat_record_media_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat_room",
            name="notes",
        ),
        migrations.AddField(
            model_name="chat_room",
            name="pin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chat_record",
            name="message_id",
            field=models.UUIDField(
                default=uuid.UUID("6362c800-2552-46a9-bde4-30f29b94f5c6"),
                editable=False,
            ),
        ),
    ]
