# Generated by Django 5.0.6 on 2025-01-08 00:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0015_remove_chat_room_notes_chat_room_pin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat_room",
            name="ban",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chat_record",
            name="message_id",
            field=models.UUIDField(
                default=uuid.UUID("e3dfe203-4a87-4ed1-93e8-cc0c1682bde4"),
                editable=False,
            ),
        ),
    ]
