# Generated by Django 5.0.6 on 2025-01-20 07:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0016_chat_room_ban_alter_chat_record_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat_record",
            name="room_path",
            field=models.TextField(blank=True, default="text"),
        ),
        migrations.AlterField(
            model_name="chat_record",
            name="message_id",
            field=models.UUIDField(
                default=uuid.UUID("5ba3cbfa-82ef-49ec-99e9-36d31db94710"),
                editable=False,
            ),
        ),
    ]
