# Generated by Django 5.0.6 on 2025-04-17 08:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0017_chat_record_room_path_alter_chat_record_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat_record",
            name="message_id",
            field=models.UUIDField(
                default=uuid.UUID("35967f32-6c9c-4d38-9ff7-1471ac7b0c3e"),
                editable=False,
            ),
        ),
    ]
