# Generated by Django 5.0.6 on 2025-04-17 08:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0018_alter_chat_record_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat_record",
            name="message_id",
            field=models.UUIDField(
                default=uuid.UUID("be2b6dfb-3639-49a9-903b-0f5a328c29bf"),
                editable=False,
            ),
        ),
    ]
