# Generated by Django 5.0.6 on 2025-04-17 08:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0019_alter_chat_record_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat_record",
            name="message_id",
            field=models.UUIDField(
                default=uuid.UUID("b3f1ce23-99de-431a-a204-0c3372761c19"),
                editable=False,
            ),
        ),
    ]
