# Generated by Django 5.0.6 on 2025-04-19 02:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_alter_chat_record_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_record',
            name='message_id',
            field=models.UUIDField(default=uuid.UUID('0b8b7dc2-9777-4a8e-9293-01d943b8da29'), editable=False),
        ),
    ]
