# Generated by Django 5.0.6 on 2025-04-19 02:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_alter_chat_record_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_record',
            name='message_id',
            field=models.UUIDField(default=uuid.UUID('d709216e-b771-4f3e-8f52-73574d3a6e97'), editable=False),
        ),
    ]
