# Generated by Django 5.0.6 on 2025-04-23 06:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0024_alter_chat_record_message_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat_record",
            name="message_id",
            field=models.UUIDField(
                default=uuid.UUID("4a42c87f-b5c9-4fd8-bbeb-a270a5ff9500"),
                editable=False,
            ),
        ),
    ]
