# Generated by Django 5.0.6 on 2025-04-24 05:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_alter_chat_record_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_record',
            name='message_id',
            field=models.UUIDField(default=uuid.UUID('c27d5834-ec43-444f-8520-81451051b4ec'), editable=False),
        ),
    ]
