# Generated by Django 5.0.6 on 2025-04-24 06:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_alter_chat_record_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_record',
            name='message_id',
            field=models.UUIDField(default=uuid.UUID('7bce2df9-3e95-4d52-9ab3-19c25a1fd2e9'), editable=False),
        ),
    ]
