# Generated by Django 5.0.6 on 2025-09-24 05:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_alter_chat_record_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_record',
            name='content_trans',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='chat_record',
            name='message_id',
            field=models.UUIDField(default=uuid.UUID('87f00fa4-aea2-4e72-989c-f93c43ae997d'), editable=False),
        ),
    ]
