# Generated by Django 5.0.6 on 2024-10-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_hashcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
    ]
