# Generated by Django 5.0.6 on 2025-09-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
    ]
