# Generated by Django 5.0.6 on 2025-09-27 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_nationality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nationality',
            new_name='user_lang',
        ),
    ]
