# Generated by Django 5.0.6 on 2025-04-19 02:26

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wound_recognize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_user', models.TextField(blank=True)),
                ('token_used', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True, default='')),
                ('ban', models.BooleanField(default=False)),
                ('photo_url', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[1920, 1080], upload_to='chat/')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wound_recognize',
            },
        ),
    ]
