# Generated by Django 5.0.6 on 2025-05-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("linerobot", "0002_user_linebot_track_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_linebot_track",
            name="chart_id",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="user_linebot_track",
            name="true_name",
            field=models.TextField(blank=True, default=""),
        ),
    ]
