# Generated by Django 5.0.6 on 2025-09-09 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(help_text='需要翻譯的原始文字內容', verbose_name='原始文字')),
                ('translated_text', models.TextField(blank=True, help_text='翻譯後的文字內容', null=True, verbose_name='翻譯結果')),
                ('source_language', models.CharField(default='en', help_text='原始文字的語言代碼', max_length=10, verbose_name='來源語言')),
                ('target_language', models.CharField(default='zh-tw', help_text='翻譯目標語言代碼', max_length=10, verbose_name='目標語言')),
                ('translation_model', models.CharField(default='gemma3:4b', help_text='使用的翻譯模型名稱', max_length=50, verbose_name='翻譯模型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('translation_time', models.FloatField(blank=True, help_text='翻譯處理時間(秒)', null=True, verbose_name='翻譯耗時')),
            ],
            options={
                'verbose_name': '翻譯記錄',
                'verbose_name_plural': '翻譯記錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
